const SOUNDS = [
  { id: "peido", emoji: "💨", label: "Peido", file: "sounds/peido.mp3" },
  { id: "peido_epico", emoji: "🤭", label: "Peido Épico", file: "sounds/peido_epico.mp3" },
  { id: "gargalhada", emoji: "😂", label: "Gargalhada", file: "sounds/gargalhada.mp3" },
  { id: "risada_galera", emoji: "🤣", label: "Risada da Galera", file: "sounds/risada_galera.mp3" },
  { id: "risadinha_boba", emoji: "😆", label: "Risadinha Boba", file: "sounds/risadinha_boba.mp3" },
  { id: "risada_maligna", emoji: "😈", label: "Risada Maligna", file: "sounds/risada_maligna.mp3" },
  { id: "fiu_fiu", emoji: "😏", label: "Fiu-Fiu", file: "sounds/fiu_fiu.mp3" },
  { id: "apito_juiz", emoji: "🧑‍⚖️", label: "Apito de Juiz", file: "sounds/apito_juiz.mp3" },
  { id: "bem_te_vi", emoji: "🐦", label: "Bem-te-vi", file: "sounds/bem_te_vi.mp3" },
  { id: "buzina_palhaco", emoji: "🤡", label: "Buzina de Palhaço", file: "sounds/buzina_palhaco.mp3" },
  { id: "trombone_tristeza", emoji: "😢", label: "Trombone da Tristeza", file: "sounds/trombone_tristeza.mp3" },
  { id: "decepcao", emoji: "🙄", label: "Que Decepção", file: "sounds/decepcao.mp3" },
  { id: "boing", emoji: "🤾", label: "Boing!", file: "sounds/boing.mp3" },
  { id: "grito_pavor", emoji: "😱", label: "Grito de Pavor", file: "sounds/grito_pavor.mp3" },
  { id: "espirro", emoji: "🤧", label: "Espirro Toon", file: "sounds/espirro.mp3" },
  { id: "beijinho", emoji: "😘", label: "Beijinho", file: "sounds/beijinho.mp3" },
  { id: "rufar_tambor", emoji: "🥁", label: "Ba Dum Tss", file: "sounds/rufar_tambor.mp3" },
  { id: "aplausos", emoji: "👏", label: "Aplausos", file: "sounds/aplausos.mp3" },
  { id: "reprovado", emoji: "❌", label: "Reprovado", file: "sounds/reprovado.mp3" },
  { id: "sininho_vitoria", emoji: "🔔", label: "Sininho da Vitória", file: "sounds/sininho_vitoria.mp3" },
  { id: "explosao", emoji: "💥", label: "Explosão", file: "sounds/explosao.mp3" },
  { id: "sistema_travou", emoji: "🖥️", label: "Sistema Travou", file: "sounds/sistema_travou.mp3" },
  { id: "bonus_extra", emoji: "🎉", label: "Bônus Extra", file: "sounds/bonus_extra.mp3" },
  { id: "piano_fracasso", emoji: "🎹", label: "Piano do Fracasso", file: "sounds/piano_fracasso.mp3" },
];
